version: '3.8'

services:
  fastapi_app:
    image: gymbro-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5400:5400"
    volumes:
      - .:/app
    command: ["hypercorn", "app:app", "--bind", "0.0.0.0:5400", "--reload"]
    restart: always
